# Generated by Django 6.0.1 on 2026-01-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20)),
                ('priorite', models.IntegerField(default=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='agents.agent')),
            ],
        ),
    ]
