# Generated by Django 6.0.1 on 2026-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='affectation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contribution',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contribution',
            name='niveau_habilitation',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contribution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='region',
            field=models.CharField(blank=True, default='CENTRE', max_length=100),
        ),
        migrations.AddField(
            model_name='contribution',
            name='specialites',
            field=models.TextField(blank=True, help_text='Liste séparée par des virgules'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
