# Generated by Django 6.0.1 on 2026-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_contribution_affectation_contribution_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='agents/photos/'),
        ),
    ]
