# Generated by Django 6.0.1 on 2026-01-09 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='affectation',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='niveau_habilitation',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='region',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='specialites',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='contribution',
            name='decision_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contribution',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fonction',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('VALIDATED', 'Validée')], default='DRAFT', max_length=20),
        ),
    ]
