# Generated by Django 6.0.1 on 2026-01-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_contribution_affectation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('REJECT_CONTRIBUTION', 'Rejet de contribution'), ('VIEW_AUDIT', "Consultation de l'audit")], max_length=30)),
                ('target_repr', models.CharField(blank=True, help_text="Représentation textuelle de la cible de l'action", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
