# Generated by Django 6.0.1 on 2026-01-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='statut',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée')], default='DRAFT', max_length=20),
        ),
    ]
