# Generated by Django 6.0.1 on 2026-01-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_contribution_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='report',
            field=models.TextField(blank=True, default='', verbose_name='Rapport de mission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('REJECT_CONTRIBUTION', 'Rejet de contribution'), ('VIEW_AUDIT', "Consultation de l'audit"), ('UPDATE_MISSION', 'Mise à jour de mission')], max_length=30),
        ),
    ]
