# Generated by Django 6.0.1 on 2026-01-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_mission_report_mission_reported_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('REJECT_CONTRIBUTION', 'Rejet de contribution'), ('VIEW_AUDIT', "Consultation de l'audit"), ('UPDATE_MISSION', 'Mise à jour de mission'), ('VIEW_PRESIDENCE_BRIEFING', 'Vue Briefing Présidence')], max_length=30),
        ),
    ]
