# Generated by Django 6.0.1 on 2026-01-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision')], max_length=30),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la décision')),
                ('decision_type', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel'), ('STRATEGIQUE', 'Stratégique')], default='OPERATIONNEL', max_length=20)),
                ('level', models.CharField(choices=[('CHEF', 'Chef de service'), ('PRESIDENCE', 'Présidence')], default='CHEF', max_length=20)),
                ('decision', models.CharField(choices=[('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ORDONNEE', 'Ordonnée')], max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire de décision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.contribution')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
