# Generated by Django 6.0.1 on 2026-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_auditlog_action_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles')], max_length=30),
        ),
    ]
