# Generated by Django 6.0.1 on 2026-01-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement')], max_length=40),
        ),
        migrations.CreateModel(
            name='RecoupementTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('CLOSED', 'Clôturé')], default='OPEN', max_length=20)),
                ('level', models.CharField(choices=[('YELLOW', 'Jaune'), ('ORANGE', 'Orange'), ('RED', 'Rouge')], default='YELLOW', max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('evidence', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('window_hours', models.IntegerField(default=72)),
                ('source', models.CharField(default='weak_signals', max_length=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.service')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recoupements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recoupements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
