# Generated by Django 6.0.1 on 2026-01-11 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_auditlog_action_recoupementticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoupementticket',
            name='assigned_service',
        ),
        migrations.RemoveField(
            model_name='recoupementticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='recoupementticket',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_recoupements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoupementticket',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_recoupements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement')], max_length=40),
        ),
        migrations.CreateModel(
            name='RecoupementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('confidence', models.IntegerField(default=2, help_text='Niveau de confiance de la réponse (1=Faible, 2=Moyen, 3=Élevé)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoupement_responses', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='agents.recoupementticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
