# Generated by Django 6.0.1 on 2026-01-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_remove_recoupementticket_assigned_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='related_recoupement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_missions', to='agents.recoupementticket'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement'), ('CHEF_ESCALATE_RECOUPEMENT', 'Chef: escalade en mission')], max_length=40),
        ),
    ]
