# Generated by Django 6.0.1 on 2026-01-11 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_mission_related_recoupement_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement'), ('CHEF_ESCALATE_RECOUPEMENT', 'Chef: escalade en mission'), ('PRESIDENCE_CREATE_ORDER', 'Présidence: création ordre'), ('PRESIDENCE_SIGN_ORDER', 'Présidence: signature ordre'), ('PRESIDENCE_EXECUTE_ORDER', 'Présidence: exécution ordre')], max_length=40),
        ),
        migrations.CreateModel(
            name='PresidentialOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order_type', models.CharField(choices=[('DIRECTIVE', 'Directive'), ('OPERATION', 'Opération'), ('URGENCE', 'Urgence')], default='DIRECTIVE', max_length=20)),
                ('classification', models.CharField(choices=[('CONFIDENTIEL', 'Confidentiel'), ('SECRET', 'Secret'), ('TRES_SECRET', 'Très Secret')], default='CONFIDENTIEL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SIGNED', 'Signé'), ('EXECUTED', 'Exécuté'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_orders', to='agents.contribution')),
                ('related_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_orders', to='agents.mission')),
                ('related_recoupement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_orders', to='agents.recoupementticket')),
                ('target_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
