# Generated by Django 6.0.1 on 2026-01-11 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_auditlog_action_presidentialorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement'), ('CHEF_ESCALATE_RECOUPEMENT', 'Chef: escalade en mission'), ('PRESIDENCE_CREATE_ORDER', 'Présidence: création ordre'), ('PRESIDENCE_SIGN_ORDER', 'Présidence: signature ordre'), ('PRESIDENCE_EXECUTE_ORDER', 'Présidence: exécution ordre'), ('AGENT_STATUS_CHANGE', 'Agent: changement statut'), ('MICROTASK_CLAIMED', 'Agent: micro-tâche prise en charge'), ('MICROTASK_COMPLETED', 'Agent: micro-tâche complétée'), ('FIELD_OBSERVATION_CREATED', 'Agent: observation terrain créée'), ('CRISIS_MODE_ON', 'Crise: mode activé'), ('CRISIS_MODE_OFF', 'Crise: mode désactivé')], max_length=40),
        ),
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PATROL', 'En patrouille'), ('RECOUPEMENT', 'En recoupement'), ('MISSION', 'En mission')], default='AVAILABLE', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=120)),
                ('mood', models.CharField(choices=[('CALM', 'Calme'), ('TENSE', 'Tendue'), ('UNUSUAL', 'Inhabituelle'), ('CRITICAL', 'Critique')], default='CALM', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLAIMED', 'Prise en charge'), ('DONE', 'Terminée')], default='OPEN', max_length=20)),
                ('task_type', models.CharField(choices=[('SUMMARIZE', 'Résumer contenu'), ('TAG_KEYWORDS', 'Taguer mots-clés'), ('RATE_RELIABILITY', 'Évaluer fiabilité'), ('WATCH_THEME', 'Surveiller thème'), ('VERIFY_INFO', 'Vérifier information')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_microtasks', to=settings.AUTH_USER_MODEL)),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.contribution')),
                ('related_recoupement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.recoupementticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('confidence', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Élevé')], default=2, help_text='Niveau de confiance du résultat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microtask_responses', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='agents.microtask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RecoupementResponse',
        ),
    ]
