# Generated by Django 6.0.1 on 2026-01-12 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_alter_auditlog_action_agentstatus_fieldobservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('CONTRIBUTION_SHARED', 'Partage de contribution'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement'), ('CHEF_ESCALATE_RECOUPEMENT', 'Chef: escalade en mission'), ('PRESIDENCE_CREATE_ORDER', 'Présidence: création ordre'), ('PRESIDENCE_SIGN_ORDER', 'Présidence: signature ordre'), ('PRESIDENCE_EXECUTE_ORDER', 'Présidence: exécution ordre'), ('AGENT_STATUS_CHANGE', 'Agent: changement statut'), ('MICROTASK_CLAIMED', 'Agent: micro-tâche prise en charge'), ('MICROTASK_COMPLETED', 'Agent: micro-tâche complétée'), ('FIELD_OBSERVATION_CREATED', 'Agent: observation terrain créée'), ('CRISIS_MODE_ON', 'Crise: mode activé'), ('CRISIS_MODE_OFF', 'Crise: mode désactivé')], max_length=40),
        ),
        migrations.CreateModel(
            name='ContributionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='agents.contribution')),
                ('service_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='agents.service')),
                ('service_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to='agents.service')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contribution', 'service_destinataire')},
            },
        ),
    ]
