# Generated by Codex on 2026-01-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0020_micromission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="micromission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED", "Proposée"),
                    ("TODO", "À faire"),
                    ("IN_PROGRESS", "En cours"),
                    ("DONE", "Terminée"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
