# Generated by Codex on 2026-01-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0022_cnsavis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnsavis",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("SENT", "Transmis"),
                    ("TRANSMITTED", "Transmis"),
                ],
                default="SENT",
                max_length=20,
            ),
        ),
    ]
