# Generated by Django 6.0.1 on 2026-01-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_alter_auditlog_action_alter_cnsavis_id'),
        ('agents', '0023_cnsavis_status_transmitted'),
    ]

    operations = [
    ]
