# Generated by Codex on 2026-01-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0023_cnsavis_status_transmitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnsavis",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
