# Generated by Codex on 2026-01-12
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0025_cnsavis_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cnsavis",
            name="presidency_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuve"),
                    ("REJECTED", "Rejete"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cnsavis",
            name="decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cnsavis",
            name="decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cns_avis_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
