# Generated by Codex on 2026-01-12
from django.db import migrations


def forward_migrate_status(apps, schema_editor):
    CNSAvis = apps.get_model("agents", "CNSAvis")
    AuditLog = apps.get_model("agents", "AuditLog")
    updated = CNSAvis.objects.filter(status="TRANSMITTED").update(status="SENT")
    if updated:
        # Nettoyage statut
        AuditLog.objects.create(
            action="MIGRATE_STATUS",
            target_repr=f"CNSAvis status TRANSMITTED -> SENT ({updated})",
        )


def reverse_migrate_status(apps, schema_editor):
    CNSAvis = apps.get_model("agents", "CNSAvis")
    CNSAvis.objects.filter(status="SENT").update(status="TRANSMITTED")


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0026_cnsavis_decision_fields"),
    ]

    operations = [
        migrations.RunPython(forward_migrate_status, reverse_migrate_status),
    ]
