# Generated by Django 6.0.1 on 2026-01-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_merge_20260113_0954'),
        ('agents', '0027_cnsavis_status_normalize'),
    ]

    operations = [
    ]
