# Generated by Django 6.0.1 on 2026-01-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_merge_20260113_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('CREATE_CONTRIBUTION', 'Création de contribution'), ('SUBMIT_CONTRIBUTION', 'Soumission de contribution'), ('VALIDATE_CONTRIBUTION', 'Validation de contribution'), ('CONTRIBUTION_SHARED', 'Partage de contribution'), ('TRANSMIT', 'Transmission'), ('READ', 'Lecture'), ('PRES_DECISION', 'Validation Chef'), ('MIGRATE_STATUS', 'Migration statut'), ('CNS_AVIS_CREATED', 'CNS: creation avis'), ('UPDATE_MISSION', 'Mise à jour de mission'), ('CREATE_DECISION', 'Création de Décision'), ('VIEW_RDC_MAP_STATUS', 'Vue Statut Carte RDC'), ('SYSTEM_WEAK_SIGNALS', 'Calcul des signaux faibles'), ('CHEF_CREATE_RECOUPEMENT', 'Chef: ouverture recoupement'), ('CHEF_TAKE_RECOUPEMENT', 'Chef: prise en charge recoupement'), ('CHEF_CLOSE_RECOUPEMENT', 'Chef: clôture recoupement'), ('CHEF_ASSIGN_RECOUPEMENT', 'Chef: assignation recoupement'), ('AGENT_REPLY_RECOUPEMENT', 'Agent: réponse recoupement'), ('CHEF_ESCALATE_RECOUPEMENT', 'Chef: escalade en mission'), ('PRESIDENCE_CREATE_ORDER', 'Présidence: création ordre'), ('PRESIDENCE_SIGN_ORDER', 'Présidence: signature ordre'), ('PRESIDENCE_EXECUTE_ORDER', 'Présidence: exécution ordre'), ('AGENT_STATUS_CHANGE', 'Agent: changement statut'), ('MICROTASK_CLAIMED', 'Agent: micro-tâche prise en charge'), ('MICROTASK_COMPLETED', 'Agent: micro-tâche complétée'), ('FIELD_OBSERVATION_CREATED', 'Agent: observation terrain créée'), ('CRISIS_MODE_ON', 'Crise: mode activé'), ('CRISIS_MODE_OFF', 'Crise: mode désactivé')], max_length=40),
        ),
    ]
